services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4
    networks:
      - backend

  app:
    build:
      context: .
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - EXTERNAL_PORT=${EXTERNAL_PORT}
        - DB_RESET_ON_START=${DB_RESET_ON_START}
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    environment:
      SQLALCHEMY_DATABASE_URL: "mysql+pymysql://root:rootpassword@database:3306/testdb"
    ports:
      - "${EXTERNAL_PORT}:${EXTERNAL_PORT}"
    networks:
      - backend
    command: ["sh", "-c", "uvicorn app.main:app --reload --host 0.0.0.0 --port $EXTERNAL_PORT"]

volumes:
  database:

networks:
  backend:
    driver: bridge
